Introduce "max" config
zenspider/codeclimate-flog pull request #7
Opened 2017-03-15 00:24 UTC by maxjacobson

The "threshold" concept doesn't work well in a CC context, because it
creates a "sliding window" where a user can improve one method, and that
leads to creating an issue in another method.

Fixes #6

2017-03-15 00:56 UTC, ABaldwinHunter commented on README.rdoc
> +          max: 20.0
WDYT think about `max_score` to help distinguish from the `threshold` option?

2017-03-15 01:00 UTC, maxjacobson commented on README.rdoc
> +          max: 20.0
Seems more clear - SGTM

2017-03-15 01:07 UTC, ABaldwinHunter commented on lib/cc/engine/flog.rb
> +          (BASE_REMEDIATION_POINTS + (OVERAGE_REMEDIATION_POINTS * (score - config["max_score"]))).
Nice! Glad we're using the diff to inform remediation points. 

WDYT about moving this calculation out into a private method like

```
def remediation_points(score)
  ...
end
```
and just passing into the issue json
?

Works fine either way so take or leave 👍 

#metacomplexityscoring

2017-03-15 01:08 UTC, ABaldwinHunter commented on README.rdoc
> +Note: specifying a maximum allowed complexity score is optional.
Maybe mention the default explicitly here?

2017-03-15 01:09 UTC, ABaldwinHunter commented
Couple of minor comments. Great job fixing this issue! LGTM

2017-03-15 01:10 UTC, ABaldwinHunter approved these changes

2017-03-15 01:16 UTC, maxjacobson commented on lib/cc/engine/flog.rb
> +         "remediation_points" => (remediation_points score),
Is this the correct way to write this in Seattle style?

2017-03-15 01:16 UTC, maxjacobson commented on README.rdoc
> +Note: specifying a maximum allowed complexity score is optional.
👍 updated

2017-03-16 22:51 UTC, zenspider requested changes
more dialog than actual change requests...

2017-03-16 22:51 UTC, zenspider commented on lib/cc/engine/flog.rb
> +            next unless score > config["max_score"]
So I'm the kid in the 3rd grade who when taught "clockwise" and "counter-clockwise" asked "if I'm looking at the clock or if I _am_ the clock"... So, calibrate accordingly.

I'm having a hard time with calling this `max_score` when it is clearly used as a floor function.

2017-03-16 22:51 UTC, zenspider commented on lib/cc/engine/flog.rb
> +         "remediation_points" => (remediation_points score),
hah. While many of us are also lispers... "Seattle-style" just means not using any extra syntax except to clarify ambiguities. In this case, your code is fine, but I'd just have written it in the normal ruby manner `remediation_points(score)`.

2017-03-16 22:51 UTC, zenspider commented on lib/cc/engine/flog.rb
> -
Not sure why this was refactored since it wasn't to test it directly and doesn't lend any extra clarity.

2017-03-16 22:51 UTC, zenspider commented on test/test_sanity.rb
> +    exp = ["./test/test_sanity.rb", "./lib/cc/engine/flog.rb"]
Probably need to explicitly sort this and the actual result below. Filesystem ordering on linux vs osx is annoying.

2017-03-17 03:02 UTC, maxjacobson commented on test/test_sanity.rb
> +    exp = ["./test/test_sanity.rb", "./lib/cc/engine/flog.rb"]
aaah that's what explains that

2017-03-17 03:03 UTC, maxjacobson commented on lib/cc/engine/flog.rb
> +            next unless score > config["max_score"]
heh yea it all depends on perspective. it's either the "maximum allowed complexity" (how I intended it) or the "minimum problematic complexity"... agreed it's ambiguous and should be changed. I'd love to just use "threshold" except some people will already have values committed like "0.6" which isn't appropriate for this kind of threshold. Going to tentatively change this to "score_threshold". WDYT?

2017-03-24 19:32 UTC, zenspider reviewed
just a nit... otherwise looks good. I like the new tests.

2017-03-24 19:32 UTC, zenspider commented on lib/cc/engine/flog.rb
> +          round
Your rubocop config doesn't ding >80 char lines?

```ruby
remediation_points =
  ((OVERAGE_REMEDIATION_POINTS * (score - config["score_threshold"]))
   + BASE_REMEDIATION_POINTS).
    round
```

2017-03-27 03:44 UTC, merged

2017-03-28 14:14 UTC, oboxodo commented on README.rdoc
> +The default is 20.0.
Now that `max_score` was renamed `score_threshold` then maybe this comment needs rewording? "maximum allowed complexity score" seems misleading.

2017-03-28 14:38 UTC, zenspider commented
Agreed